# Generated by Django 2.2 on 2020-03-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Open', models.DecimalField(decimal_places=3, max_digits=10)),
                ('High', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Low', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Choise', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Volume', models.IntegerField()),
            ],
        ),
    ]
